### ISSUE TITLE
Adding newsltter subscription feature

### ISSUE THREAD

**Issue by Srujitha-Raghava** [mdazfar2/HelpOps-Hub#239] opened 2024-06-06 07:44 UTC
### Describe the feature

Our application aims to enhance user engagement and provide valuable content updates through a newsletter feature. This feature will allow users to subscribe to newsletters, receive regular updates via email, and manage their subscription preferences.

### Add ScreenShots

![Screenshot 2024-05-24 161622](https://github.com/mdazfar2/HelpOps-Hub/assets/143430142/5c86795f-8088-4fa2-99e7-33b3fde84c59)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Srujitha-Raghava** [comment] 2024-06-06 10:36
A newsletter feature allows you to send regular email updates to people who subscribe to your newsletter. These updates can include news, promotions, or any other content you want to share with the audience.

1. A person visits our website, enters her email, and clicks "Subscribe."
2. He/She receives an email, clicks the confirmation link, and is now subscribed.
3. You log into the admin panel, write the content for the newsletter, and schedule it to be sent next Monday.
4. He/She receives an email that says, "Hello, XYZ! Check out our latest updates and offers."
5.  A simple "Subscribe" link or button next to the main navigation menu items.


@mdazfar2 Hope you understand!

**Comment by mdazfar2** [comment] 2024-06-06 10:50
@Srujitha-Raghava Nice idea! But who send mails is it automatically or we have to send mail by manually?

**Comment by Srujitha-Raghava** [comment] 2024-06-06 11:11
@mdazfar2 YES, we can send automatically by using an email service provider (ESP) like Mailchimp or similar to handle the automatic sending of emails.

Manual Email sending can be works as follows:
1. You create the newsletter content in the admin interface.
2. You manually click a button to send the newsletter when you're ready.
3. This method gives you more control over the exact timing of each email.

**Comment by mdazfar2** [comment] 2024-06-06 11:33
> @mdazfar2 YES, we can send automatically by using an email service provider (ESP) like Mailchimp or similar to handle the automatic sending of emails.
> 
> Manual Email sending can be works as follows:
> 
> 1. You create the newsletter content in the admin interface.
> 2. You manually click a button to send the newsletter when you're ready.
> 3. This method gives you more control over the exact timing of each email.

@Srujitha-Raghava, we don't have time to send the latest tech news manually. Automate this process and try to send emails about DevOps news or the latest DevOps updates. Could you do that? Remember, it is your full responsibility. You can also work with your own team. I will give a GSSOC Level 3 label, If it is full fuctionally.

**Comment by mdazfar2** [comment] 2024-06-11 23:31
Hey @Srujitha-Raghava, please let me know the status. It's been almost 5 days and you haven't responded.

**Comment by Srujitha-Raghava** [comment] 2024-06-12 09:36
Hey @mdazfar2 sorry for not intimating, I'm having exams rn,i haven't started working yet! I'll start from 16th of this month!

**Comment by mdazfar2** [comment] 2024-06-12 09:37
best of luck for your exam @Srujitha-Raghava

**Comment by vansh-codes** [comment] 2024-06-19 22:34
@mdazfar2 @Srujitha-Raghava I can help in adding feature like automated welcome mail when user subscribes to newsletter. As soon as the user subscribes to the newsletter, an automated email will be sent to the user. The welcome mail may contain:
what the website is about, what's the purpose of newsletter in this website. 
Why is it necessary to send a welcome email?
People often subscribe and forget about the website, a welcome mail will make them familiar with the mail id the website would be using to share newsletters so next time when they see a main they would recall everything. 
This would need backend server like nodejs and express to be integrated in this project. If this is integrated then routing can be implemented which would make the url paths more convenient and easier to understand. For example: 
In the home page, the url is "https://www.helpopshub.com/abouts.html", on adding routing this could be "https://www.helpopshub.com/about", the file type can be excluded and we would have our choice on how to make the url.

Let me know your thoughts on all this!!

**Comment by mdazfar2** [comment] 2024-06-20 03:28
@vansh-codes that's a nice idea 

- First, clarify what type of welcome mail you prefer. Do you have any specific text or message in mind?
- It would be great if users could get the latest news related to DevOps, the latest DevOps tools, or anything else.
- Actually, we are converting the code to NEXTJS, and it will take 2 to 3 days to complete. After completion, it will be easy to integrate with the backend.
- I would request you guys to please discuss on [Discord](https://discord.gg/UWTrRhqywt) what type of message and what else can be added to the newsletter.

**Comment by vansh-codes** [comment] 2024-06-20 05:46
> @vansh-codes that's a nice idea
> 
> * First, clarify what type of welcome mail you prefer. Do you have any specific text or message in mind?
> * It would be great if users could get the latest news related to DevOps, the latest DevOps tools, or anything else.
> * Actually, we are converting the code to NEXTJS, and it will take 2 to 3 days to complete. After completion, it will be easy to integrate with the backend.
> * I would request you guys to please discuss on [Discord](https://discord.gg/UWTrRhqywt) what type of message and what else can be added to the newsletter.

I haven't thought of a specific text template yet, but if you say so I can raise a issue and then start working on it. 
@mdazfar2 I just had a addon idea on @Srujitha-Raghava 's idea about newsletter. She can manage the automatically sending mails to keep the user updated about latest news. My idea was to send a welcome mail as soon as the user subscribes to the newsletter. 
This email serves several important purposes:
- Welcome and Acknowledge: It thanks the new subscriber for joining the mailing list and acknowledges their subscription.
- Introduction: It introduces the brand or organization, providing a brief overview of what the subscriber can expect from the newsletter.
- Set Expectations: It outlines the type of content, frequency of emails, and any other relevant details about what the subscriber can expect.
- Engagement: It encourages further engagement, such as following the brand on social media, visiting the website, or exploring popular content.
- Personalization: It often includes personalized content, making the subscriber feel valued and appreciated.

I hope now you've got my point. If you agree then I will start working on the template of welcome email but would need your inputs and feedbacks in the process to make the best one. 
Let me know your thoughts then I would connect with Srujitha to collaborate and start working.

**Comment by mdazfar2** [comment] 2024-06-20 06:13
@vansh-codes I will tell you in 3-4 days because, by that time, all the code converted to NEXTJS will be updated. It is easy to integrate with backend and all

**Comment by vansh-codes** [comment] 2024-06-20 06:38
> @vansh-codes I will tell you in 3-4 days because, by that time, all the code converted to NEXTJS will be updated. It is easy to integrate with backend and all 

Okay sure! Would be waiting 🙌

**Comment by mdazfar2** [comment] 2024-06-23 20:10
Hey @vansh-codes @Srujitha-Raghava, now the code has been converted and deployed successfully on `Next.js`. Now you guys can work together.
- The whole code is in the `website3.0` folder.
- Hope you read the [CONTRIBUTING Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md).
- Please try to add comments about where and what type of changes you made.
- Please don't add unnecessary code if there is no need! Thanks :)

**Comment by vansh-codes** [comment] 2024-06-23 20:53
> Hey @vansh-codes @Srujitha-Raghava, now the code has been converted and deployed successfully on `Next.js`. Now you guys can work together.
> - The whole code is in the `website3.0` folder.
> - Hope you read the [CONTRIBUTING Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md).
> - Please try to add comments about where and what type of changes you made.
> - Please don't add unnecessary code if there is no need! Thanks :)

**Comment by mdazfar2** [comment] 2024-06-23 20:58
@vansh-codes you can contact me via-

- [Discord](https://discordapp.com/users/877531143610708028)
or
 - [Linkedin](https://linkedin.com/in/md-azfar-alam/)

**Comment by vansh-codes** [comment] 2024-06-23 20:59
> @vansh-codes you can contact me via-
> 
> - [Discord](https://discordapp.com/users/877531143610708028)
> or
>  - [Linkedin](https://linkedin.com/in/md-azfar-alam/)

What about the issue? Shall I raise one?

**Comment by shreyash3087** [comment] 2024-06-25 16:03
@mdazfar2 If the issue is not currently being addressed by anyone,i can handle it.
I would implement proper newletter subscription functionality using mailchimp in nextjs
This would allow Helpops to send welcome email to user like the one given below-


------------------------------------------------------------------------------------
Subject: Welcome to HelpOps-Hub! Your DevOps Journey Starts Here

Hi [Recipient's Name],

Welcome to HelpOps-Hub! We’re thrilled to have you join our community dedicated to mastering DevOps.

At HelpOps-Hub, you’ll discover a wealth of resources designed to make your DevOps journey smoother. Our platform offers:

- Expert insights and solutions for your toughest DevOps challenges.
- Interactive tutorials and hands-on labs.
- Personalized learning paths tailored to your goals.
- A vibrant community for collaborative problem-solving and innovation.
- Get started by exploring our resources and connecting with fellow DevOps enthusiasts.

Happy DevOps-ing!

Best regards,
The HelpOps-Hub Team


---------------------------------------------------------------------------------------------



This would also you to send announcement mails to users about any new updates,also if you want to send automated mails to users abouts any new updates in Devops,you can do it easily through your mailchimp account

**Comment by mdazfar2** [comment] 2024-06-25 16:09
Hey @shreyash3087, thanks for sharing the details about it and confirming what exactly we are going to implement.

- I'll create a Discord channel for the newsletter and will invite both of you to discuss it.

**Comment by mdazfar2** [comment] 2024-06-28 07:46
This issue was solved by reference PR #705.

**Closed by mdazfar2** 2024-06-28 07:46 UTC
Labels: enhancement, gssoc, level3, web enhance, assigned, work done, fav issue
