### ISSUE TITLE
Add Hover Effect to Benefits Cards in About Section of HelpOps Hub

### ISSUE THREAD

**Issue by Manikant69** [mdazfar2/HelpOps-Hub#1400] opened 2024-10-15 11:13 UTC
### Description

The **Benefits of HelpOps Hub** cards in the About section currently lack a hover effect, which can improve the interactivity and user experience. Adding a hover effect to these cards would visually enhance the user’s engagement with the content, making it more dynamic and appealing.

#### Expected Behavior:
- When hovering over the **Benefits** cards, a visual effect (such as a shadow, scaling, or color change) should be applied to indicate interactivity.

### Screenshots

![image](https://github.com/user-attachments/assets/c401cba7-0994-4b4b-bc21-388bddc808b2)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [ ] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment] 2024-10-15 14:11
@Manikant69, issue acknowledged! You're assigned.

- Please ensure the hover effect is subtle and doesn't linger too long. A smooth, gradual transition would create a more visually appealing and professional look.

**Comment by Manikant69** [comment] 2024-10-15 22:59
ok

**Comment by Manikant69** [comment] 2024-10-19 23:51
the alignment of these cards are also not as all cards in this app

## other cards alignment from left and right
![image](https://github.com/user-attachments/assets/10c8b7cb-0a9e-45cb-ba61-a92eeb62c49b)
![image](https://github.com/user-attachments/assets/b2be34a4-23ef-43ac-824a-ae7008e47a16)

##but the alignment of this card is from right and left is not good
![image](https://github.com/user-attachments/assets/ec9336bb-9701-4dcb-88a8-304d1e5f125a)

**Comment by Manikant69** [comment] 2024-10-19 23:52
so confirm me to work on this

**Comment by mdazfar2** [comment] 2024-10-20 15:09
Hey @Manikant69, actually, this is what we want. This is not a bug; it is intended to be exactly like this. Please raise another issue, which I'm happy to assign to you. However, make sure that the issue you raise is valid and genuinely needs to be addressed on our website; _Thank you!_

**Comment by Manikant69** [comment] 2024-10-20 18:10
i am not taking about second image just check the 3rd image in that image the gap from left and right is not good as all other cards

**Closed** 2024-11-21 01:36 UTC
Labels: bug, assigned, hacktoberfest, hacktoberfest-accepted
