### ISSUE TITLE
[BUG] Enhance contact us

### ISSUE THREAD

**Issue by AswaniBolisetti** [mdazfar2/HelpOps-Hub#1423] opened 2024-10-23 11:31 UTC
### Description

@mdazfar2 
I would like to enhance contact us page, could you please assign it to me

### Screenshots

![contact](https://github.com/user-attachments/assets/609c8f4c-740c-468a-9dfe-49e8daa503dc)

![contact2](https://github.com/user-attachments/assets/2c520791-6897-4414-ade0-f988d4500a18)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment] 2024-10-23 15:14
@AswaniBolisetti, the Contact Us page looks good and correct on our side. Please check again, there might be a network issue on your end. Check out the below screenshot as proof. Sorry for any inconvenience. I am closing the issue for now. Please don't be discouraged, and feel free to raise any other issue, but ensure that the issue is really needed for our website. Otherwise, invalid issues might be closed.


![image](https://github.com/user-attachments/assets/999bd047-2eb6-4c2a-b01b-dc5e2474d7fd)

**Closed** 2024-10-23 15:14 UTC
Labels: bug
